### ISSUE TITLE
Why isn't Composite its own type extending Buffer?

### ISSUE THREAD

**Issue by ejona86** [netty/netty-incubator-buffer-api#47]
I don't see the point of the Composite API being directly on the Buffer API. Why not move it out to an interface or concrete class with only the additional method `extendComposite()`? It could be created/returned from BufferAllocator directly. Using a final class would allow safely managing unwrapping of composites during extendComposite, but there's obviously tradeoffs there.

I'd generally consider it to be a code smell to call `isComposite()` on a buffer the code didn't create, which means there should very rarely be any calls to `isComposite()`. For most usages, returning the clear type from BufferAllocator seems clearer.

If there's doubt as to which approach is best, maybe the decision here will become more obvious as more code is written using the new API.

**Comment by jameskleeh** [comment]
Agreed. Having `Buffer.isComposite` is not a great design imo. If you need to know if its a composite then that should indicate it should be a separate public class.

**Comment by chrisvest** [comment]
The compose method was initially on the BufferAllocator interface, but since there's only one fixed implementation, it didn't make sense to let the allocator implementation decide how buffer composition works. I think we still need to create composite buffers with a static factory method somewhere.

I think at this point, with a compose overload to deal with #45, we would have 4 methods that are composite buffer specific, so maybe collecting them in their own interface makes sense. Should this interface be only those static methods, or should composite buffers implement this interface? If the latter, should the interface extend Buffer? As much as possible I want buffers to behave the same regardless of implementation, but composite buffers have a few important differences to them, and I haven't yet found an argument that nails that composite buffers must be done one way or another.

**Comment by ejona86** [comment]
> The compose method was initially on the BufferAllocator interface, but since there's only one fixed implementation, it didn't make sense to let the allocator implementation decide how buffer composition works. I think we still need to create composite buffers with a static factory method somewhere.

If composite buffer was a final class then the allocator wouldn't get to choose the implementation, only how to construct it. I guess `compose()` is less interesting for this issue than `extendComposite()`. We could leave the current Buffer.compose() method and just have it return a Composite type. I do find it to be weird for Buffer to depend on Allocator and vise versa, sort of needlessly, but I don't think it has much functional impact and we may end up bikeshedding about that detail.

> Should this interface be only those static methods

I think this issue was "why are there these static methods for something that is clearly a type-specific method?" So there should be some non-static methods. Once you deal with the non-static methods, the static ones may fall into place.

> Should this interface be only those static methods, or should composite buffers implement this interface? If the latter, should the interface extend Buffer?

If there is a composite interface/class with non-static methods, then I do think it needs to extend Buffer, or have an adapter to buffer. The entire point of composite is that it is a stand-in for Buffer.

**Comment by chrisvest** [comment]
A buffer needs to know about its allocator in order to implement `ensureWritable`.
