### ISSUE TITLE
Composite buffer API

### ISSUE THREAD

**Issue by jameskleeh** [netty/netty-incubator-buffer-api#48]
We also need a way to release a section of a composite buffer. This need and the current shortcomings of the current file upload API are described here netty/netty#8655. See https://github.com/micronaut-projects/micronaut-core/blob/2.4.x/http-server-netty/src/main/java/io/micronaut/http/server/netty/HttpDataReference.java#L221-L243

Basically the composite buffer API currently has methods to retrieve and release individual buffers within the composite. We need this functionality to support streaming file uploads.

**Comment by chrisvest** [comment]
The section you want to release would be at either the start of the buffer or the end, right?
In that case, you can split the buffer in two with bifurcate and release one of the two resulting parts. It's not super convenient if you really want to release components, since bifurcate works with byte offsets, and if you're off by one you'll end up with a bifurcated component in your composite buffer parts.

**Comment by chrisvest** [comment]
To your other point; http upload definitely needs some love. I've already ported over an example, but it's not using the new APIs throughout. Maybe it would be a good exercise to try and build another example using the new APIs.

**Comment by jameskleeh** [comment]
@chrisvest The section that would be released in my use case would almost always be at the start of the buffer. I can't think of a valid use case where it would be in the middle, however I do need to reference many sections of the buffer. In the case where the upload is not read immediately, the components are stored and then released later.

**Comment by chrisvest** [comment]
@jameskleeh I've been thinking that working with component indexes don't quite make sense, because 1) it's hard to obtain indexes to components; you have to use one of the `forEach…` methods to count, and 2) component indexes are not used or exposed anywhere else.

I think it would be better to have a bifurcate (or split, #52) method that takes a byte offset, but rounds either up or down to nearest component. I'm not sure which rounding direction is more useful, or if both are needed. When #51 is in, I think this could make sense as a functionality specific to composite buffers. On regular buffers, since they only and always have exactly one component, this rounding would always cause one of the resulting buffers to be empty, which doesn't sound very useful.
