### ISSUE TITLE
Ownership model discussion

### ISSUE THREAD

**Issue by chrisvest** [netty/netty-incubator-buffer-api#56]
Copying @ejona86 from https://github.com/netty/netty-incubator-buffer-api/pull/54#pullrequestreview-650525306

> Honestly, I think this problem is just evidence that the ownership model is wrong. If you don't own a Buffer, the Buffer is nerfed and is mostly unusable. The general approach in practice I expect will be "never make buffers unowned" and this change further confirms it. I think it needs to be addressed head-on: either change the ownership/refcounting model so buffers don't become useless when backing memory is shared or change the model so there is no need to expose when backing memory is shared such that they are always owned. For example, to avoid exposing shared backing memory, this copy-on-write approach could be general-purpose.

Let's take a look. Suppose we want buffers to have ownership at all times, what would that look like? There are only two operations that can cause a buffer to loose ownership: acquire and slice. We will have to get rid of these in order to let buffers have ownership at all times.

We could probably live without acquire without too much trouble, but slice is a little harder. The slice methods let you, perhaps temporarily, focus on a sub-section of a buffer, for reading (IO into buffer), writing (IO out of buffer), or processing. I see the following alternatives to slicing:

* Rely on offsets. Buffers already have reader and writer offsets, and we could also pass explicit offset and length arguments to any method that operates on a buffer. This has precedent with IO methods, so those use cases are perhaps not a big worry. Processing comes in two varieties, as I see it. The first is to break a larger buffer into smaller parts, such as frames, packets, objects, chunks. This could also be solved with split. The second involve doing some work on a small section of the buffer, as part of some larger processing. There are not many examples of this in Netty. This could be decoding a length prefixed string, making a buffer of zeros of a particular length, searching for some header. These could be solved by passing explicit length arguments. That's something that would then need to be taken into account every such an API is created.
* Always copy. Instead of slices sharing the underlying memory with their parent, we could produce buffers that contain copies of the relevant sections of memory. This might work for writing and more processing, but it would not work for reading. IO would have to rely on offsets in this case. A drawback of this approach is the overhead involved in all the memory copies.
* Slice objects. These would be objects that hold a reference to the relevant buffer (but without incrementing a reference count), and have a base offset and a length. These would effectively act like buffers but without being buffers themselves. We could deal with this for IO, similarly to how FileRegion is handled, since that is only a small part of the code base. It would be inconvenient for processing, however. Many pieces of code would have to be duplicated, or at least made more complicated, in order to handle both buffers and slices. So what if these slice objects implement the Buffer interface? Then we will have sharing without any accounting to make the sharing safe. The slices would also be an indirection on top of the buffers. Making the sharing safe with reference counting gives us the current system that ByteBuf uses, and removing the indirection gives us the current system in the new buffer API.

Of these options, the slice objects sounds like the worst solution, so a practical approach might be a mix of the first two options.

Those are the options that I can see, for buffers maintaining ownership at all times. So what if they didn't have to do that? What if "loosing ownership" was less disruptive? There are currently 4 operations that require ownership, or their methods will throw an exception: ensureWritable, compact, split, and send. Perhaps we can define useful behaviours for these, for when they don't have ownership.

* The ensureWritable method may cause the buffers underlying memory to be reallocated. If there exist a slice from this buffer, then that slice, and the buffer it came from, would end up referring to different memory. This may be fine for writing and most processing, but it would not work for reading, that is, IO that moves data into the buffer. We could instead make all slices and their original buffer connected, such that calling ensureWritable in the original buffer will also replace the memory in all of the slices. There would be some book keeping involved, but it's doable. If we call ensureWritable on a slice, we might expand the slice's region into the space available in the original buffer. This would, however, expose them to interference from each other. Perhaps that's not common in practice. It would be inconvenient to debug if it did happen, though. We could alternatively change the semantics of ensureWritable slightly. If instead of mutating the buffer it is called on, it returns a buffer - itself or a newly allocated copy - that can be written into. This would side-step the need for ownership as it is now baked into the API that ensureWritable will never change the underlying memory of any buffer.
* The idea of compact is to discard data that has already been processed, in order to make room for more unprocessed data. Here, the choice to copy works out the same as for ensureWritable. If we instead keep track of all slices, we could adjust their offsets accordingly. This might work, as long as offsets are not kept around in other external variables or fields. That requires coding discipline at all use sites. We have seen bugs similar to this before. It might also disrupt some optimisations. Another case to consider is when compact is called on a slice. It doesn't sound useful to move the data that is in the middle of the original buffer. Perhaps compact on any of the slices or the original buffer, will use the smallest read offset of them all, and adjust all according to that? That would be safe, but the amount of data compacted would not be predictable.
* The split method breaks a buffer into two individually owned buffers. If a slice had been created off the buffer, that slice could now span two original buffers. What if we call compact or ensureWritable on this slice? Unless we go with copying, the ways in which things can interact becomes difficult to manage. Since split only exists to manage ownership, we may be able to remove it entirely, if buffer ownership is no longer such an important state of a buffer. Assuming we can find a way to let all methods always be called, regardless of ownership, then we won't have to think about what role split will have in the buffer API. This means that slice will now be carrying the use cases that were previously solved by split.
* Lastly is the send method. If ownership no longer needs to be checked, the only effect of sending a buffer is that the Buffer object being sent becomes inaccessible. This is perhaps not enough to justify the existence of the method. Since buffers can be more freely shared in this world, we could just as well share the object reference to the buffer directly, rather than wrapping it in a send object.

It turns out that how slices interact with ensureWritable and compact, are the source of pretty much all of our trouble.
We either need to find alternatives to slicing, or figure something out for ensureWritable and compact, or keep track of ownership. An option that wasn't discussed is to just get rid of ensureWritable and compact. Our buffers would then no longer be dynamically resizable, like how the JDK ByteBuffers aren't. Or we only get rid of compact, and keep the version of ensureWritable that return new buffers rather than changing the buffer it's called on.

@normanmaurer @NiteshKant @ejona86 @njhill What do you guys think?

**Comment by chrisvest** [comment]
Two things I forgot to mention:
Another option is also to give up on the safety properties. Then it is mostly a matter of what API is the most convenient.
Second, if the ensureWritable method is to produce new buffer instances instead of enlarging existing ones, it would interact poorly with the try-with-resources clause.

**Comment by ejona86** [comment]
Slice() comes up quite a few times in the discussions. However, looking through the examples, I don't actually see any serious usages of slice. Seems they could be split() or some other API. `FixedLengthFrameDecoder` it dubious as-is as the returned slice wouldn't have ownership and thus seems highly likely to break something.

But why use a slice when reading (writing to slice)? If ensureWritable will change the original buffer as well, why not just use the original buffer? What is the benefit of slice in a reading case, especially since after a read you'll want to know the new write index?

Since I'm poking at examples, I think it is a Bad Idea™ to have both Send and Buffer sent through the pipeline as done in `AlternativeMessageDecoder`. It should be one or the other.

I don't see any good examples for Send as well. It looks like SendExample.Ex6 is broken? Wouldn't all those send()s not have ownership? How is it sending the same buffer multiple times?

**Comment by chrisvest** [comment]
> It looks like SendExample.Ex6 is broken? Wouldn't all those send()s not have ownership? How is it sending the same buffer multiple times?

It works by calling split.

**Comment by ejona86** [comment]
> It works by calling split.

Doh. I read it as slice. Let it be known, I am having a _seriously_ hard time reading the difference between split and slice. Like when forming my previous comment I got them mixed up many, many times. I'd go off and do a grep and do the wrong one.

From an English perspective I guess they have mostly the same meaning and they don't look obviously-enough different to me or something. It may just be me, because I have a hard time with any two words that start with the same letter (:smile:). But we may want to keep a watch-out if it doesn't get better with time and if others suffer the same way. Sort of disappointing because bifurcate didn't cause me problem but it is is a rarely used word, so I _want_ split to work.

**Comment by chrisvest** [comment]
The names wouldn't be confusing if we got rid of slice in favour of offset parameters, copying, and split. It's an interesting idea, if there's little need for precisely what slice does. 

I'm reluctant to say it means we can also get rid of send, because it allows us to describe the ownership transfer as types.  Without it I worry it'll be too easy to accidentally share buffers.

**Comment by njhill** [comment]
I don't mind those names too much because slice also makes sense as a noun, like you are creating a new slice as opposed to splitting a buffer into two. Maybe `view` or `newView` could be used instead of slice?

@chrisvest apologies again for taking so long, I spent a bit of time yesterday catching up and have a number of other questions/comments, though still have more to cover and wrap my head around.

For this constant / buffer sharing discussion am I correct in thinking there's kind of two cases:
1. Some constant data which is never going to be released (i.e. reusable `public static final` const)
2. A buffer which has been written/manipulated but will then be shared among some number of reading threads, but still has a finite lifetime

In both these cases what is wrong with ownership being lost? Doesn't ownerless => read-only and "shared" => ownerless? i.e. there shouldn't be an expectation or need to perform any of the operations that require ownership.

What about a new `shareSlice` operation which is like slice but increases atomic refcount (and ownership is lost of course)?

But actually it looks like lack of ownership doesn't currently prevent writes.. is this intentional? Would adding that restriction help if so?

**Comment by chrisvest** [comment]
Yeah, I've been thinking that read-focused usages, loosing ownership is perhaps not a big deal as long as you can slice. But I guess it depends on how we'd like to design our APIs around this. If we try to maintain ownership at all times, we'd probably use `send` a lot for propagating buffers through the pipeline, since that's a type-level guarantee to the receiving code that they'll get ownership of the buffers.

For write-focuses usages, you'll need ownership to call `ensureWritable`. Since these buffers originate from handler code, it might be easier for people reason about their buffers life time and ownership.

> What about a new shareSlice operation which is like slice but increases atomic refcount (and ownership is lost of course)?

The current `slice` method already works like that.

> But actually it looks like lack of ownership doesn't currently prevent writes.. is this intentional? Would adding that restriction help if so?

Yes, that's intentional. You can't do IO into the buffer if it's read-only. Since there's no limit offset, slices are the way to set an IO bound less than `writableBytes`. This is certainly useful when working with files, but perhaps there's less of a need in the network oriented use cases for Netty.
